// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package jwtserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JwtServerServiceClient is the client API for JwtServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JwtServerServiceClient interface {
	GetToken(ctx context.Context, in *Reqtoken, opts ...grpc.CallOption) (*Tokenstring, error)
	CheckToken(ctx context.Context, in *CheckAuth, opts ...grpc.CallOption) (*AuthRslt, error)
}

type jwtServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJwtServerServiceClient(cc grpc.ClientConnInterface) JwtServerServiceClient {
	return &jwtServerServiceClient{cc}
}

func (c *jwtServerServiceClient) GetToken(ctx context.Context, in *Reqtoken, opts ...grpc.CallOption) (*Tokenstring, error) {
	out := new(Tokenstring)
	err := c.cc.Invoke(ctx, "/jwtserver.JwtServerService/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServerServiceClient) CheckToken(ctx context.Context, in *CheckAuth, opts ...grpc.CallOption) (*AuthRslt, error) {
	out := new(AuthRslt)
	err := c.cc.Invoke(ctx, "/jwtserver.JwtServerService/CheckToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtServerServiceServer is the server API for JwtServerService service.
// All implementations must embed UnimplementedJwtServerServiceServer
// for forward compatibility
type JwtServerServiceServer interface {
	GetToken(context.Context, *Reqtoken) (*Tokenstring, error)
	CheckToken(context.Context, *CheckAuth) (*AuthRslt, error)
	mustEmbedUnimplementedJwtServerServiceServer()
}

// UnimplementedJwtServerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJwtServerServiceServer struct {
}

func (UnimplementedJwtServerServiceServer) GetToken(context.Context, *Reqtoken) (*Tokenstring, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedJwtServerServiceServer) CheckToken(context.Context, *CheckAuth) (*AuthRslt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}
func (UnimplementedJwtServerServiceServer) mustEmbedUnimplementedJwtServerServiceServer() {}

// UnsafeJwtServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JwtServerServiceServer will
// result in compilation errors.
type UnsafeJwtServerServiceServer interface {
	mustEmbedUnimplementedJwtServerServiceServer()
}

func RegisterJwtServerServiceServer(s grpc.ServiceRegistrar, srv JwtServerServiceServer) {
	s.RegisterService(&JwtServerService_ServiceDesc, srv)
}

func _JwtServerService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reqtoken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServerServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtserver.JwtServerService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServerServiceServer).GetToken(ctx, req.(*Reqtoken))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtServerService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServerServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtserver.JwtServerService/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServerServiceServer).CheckToken(ctx, req.(*CheckAuth))
	}
	return interceptor(ctx, in, info, handler)
}

// JwtServerService_ServiceDesc is the grpc.ServiceDesc for JwtServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JwtServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jwtserver.JwtServerService",
	HandlerType: (*JwtServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _JwtServerService_GetToken_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _JwtServerService_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwtserver.proto",
}
