// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: jwtserver.proto

package jwtserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reqtoken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Reqtoken) Reset() {
	*x = Reqtoken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reqtoken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reqtoken) ProtoMessage() {}

func (x *Reqtoken) ProtoReflect() protoreflect.Message {
	mi := &file_jwtserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reqtoken.ProtoReflect.Descriptor instead.
func (*Reqtoken) Descriptor() ([]byte, []int) {
	return file_jwtserver_proto_rawDescGZIP(), []int{0}
}

func (x *Reqtoken) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type CheckAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenString string `protobuf:"bytes,2,opt,name=tokenString,proto3" json:"tokenString,omitempty"`
}

func (x *CheckAuth) Reset() {
	*x = CheckAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuth) ProtoMessage() {}

func (x *CheckAuth) ProtoReflect() protoreflect.Message {
	mi := &file_jwtserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuth.ProtoReflect.Descriptor instead.
func (*CheckAuth) Descriptor() ([]byte, []int) {
	return file_jwtserver_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAuth) GetTokenString() string {
	if x != nil {
		return x.TokenString
	}
	return ""
}

type Tokenstring struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenString string `protobuf:"bytes,1,opt,name=tokenString,proto3" json:"tokenString,omitempty"`
}

func (x *Tokenstring) Reset() {
	*x = Tokenstring{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tokenstring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokenstring) ProtoMessage() {}

func (x *Tokenstring) ProtoReflect() protoreflect.Message {
	mi := &file_jwtserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokenstring.ProtoReflect.Descriptor instead.
func (*Tokenstring) Descriptor() ([]byte, []int) {
	return file_jwtserver_proto_rawDescGZIP(), []int{2}
}

func (x *Tokenstring) GetTokenString() string {
	if x != nil {
		return x.TokenString
	}
	return ""
}

type AuthRslt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokenvalid bool   `protobuf:"varint,1,opt,name=tokenvalid,proto3" json:"tokenvalid,omitempty"`
	User       string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AuthRslt) Reset() {
	*x = AuthRslt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRslt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRslt) ProtoMessage() {}

func (x *AuthRslt) ProtoReflect() protoreflect.Message {
	mi := &file_jwtserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRslt.ProtoReflect.Descriptor instead.
func (*AuthRslt) Descriptor() ([]byte, []int) {
	return file_jwtserver_proto_rawDescGZIP(), []int{3}
}

func (x *AuthRslt) GetTokenvalid() bool {
	if x != nil {
		return x.Tokenvalid
	}
	return false
}

func (x *AuthRslt) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_jwtserver_proto protoreflect.FileDescriptor

var file_jwtserver_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6a, 0x77, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6a, 0x77, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x08,
	0x52, 0x65, 0x71, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x09,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x75, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x2f, 0x0a, 0x0b, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x3e, 0x0a, 0x08,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x73, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0x88, 0x01, 0x0a,
	0x10, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x13, 0x2e,
	0x6a, 0x77, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x1a, 0x16, 0x2e, 0x6a, 0x77, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x2e, 0x6a, 0x77, 0x74,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x75, 0x74, 0x68,
	0x1a, 0x13, 0x2e, 0x6a, 0x77, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x73, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x6a, 0x77, 0x74, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jwtserver_proto_rawDescOnce sync.Once
	file_jwtserver_proto_rawDescData = file_jwtserver_proto_rawDesc
)

func file_jwtserver_proto_rawDescGZIP() []byte {
	file_jwtserver_proto_rawDescOnce.Do(func() {
		file_jwtserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwtserver_proto_rawDescData)
	})
	return file_jwtserver_proto_rawDescData
}

var file_jwtserver_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jwtserver_proto_goTypes = []interface{}{
	(*Reqtoken)(nil),    // 0: jwtserver.Reqtoken
	(*CheckAuth)(nil),   // 1: jwtserver.CheckAuth
	(*Tokenstring)(nil), // 2: jwtserver.Tokenstring
	(*AuthRslt)(nil),    // 3: jwtserver.AuthRslt
}
var file_jwtserver_proto_depIdxs = []int32{
	0, // 0: jwtserver.JwtServerService.GetToken:input_type -> jwtserver.Reqtoken
	1, // 1: jwtserver.JwtServerService.CheckToken:input_type -> jwtserver.CheckAuth
	2, // 2: jwtserver.JwtServerService.GetToken:output_type -> jwtserver.Tokenstring
	3, // 3: jwtserver.JwtServerService.CheckToken:output_type -> jwtserver.AuthRslt
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwtserver_proto_init() }
func file_jwtserver_proto_init() {
	if File_jwtserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwtserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reqtoken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tokenstring); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRslt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwtserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwtserver_proto_goTypes,
		DependencyIndexes: file_jwtserver_proto_depIdxs,
		MessageInfos:      file_jwtserver_proto_msgTypes,
	}.Build()
	File_jwtserver_proto = out.File
	file_jwtserver_proto_rawDesc = nil
	file_jwtserver_proto_goTypes = nil
	file_jwtserver_proto_depIdxs = nil
}
